export const translations = {
  // ... vos traductions restent les mêmes ...
  en: {
    // General
    welcome: 'Welcome',
    guest: 'Guest',
    settings: 'Settings',
    logout: 'Logout',
    dashboard: 'Dashboard',
    save: 'Save',
    saving: 'Saving...',
    create: 'Create',
    edit: 'Edit',
    delete: 'Delete',
    cancel: 'Cancel',
    confirm: 'Confirm',
    success: 'Success',
    error: 'Error',
    requiredField: 'This field is required.',
    
    // Modules
    companySettings: 'Company Settings',
    administration: 'Administration',
    purchases: 'Purchases',
    sales: 'Sales',
    stock: 'Stock',
    finance: 'Finance',
    reporting: 'Reporting',
    appSettings: 'App Settings',

    // Sub-modules & Screens
    companyInfo: 'Company Information',
    employees: 'Employees',
    vehicles: 'Vehicles',
    banks: 'Banks',
    paymentMethods: 'Payment Methods',
    clients: 'Clients',
    suppliers: 'Suppliers',
    articles: 'Items',
    itemFamilies: 'Item Families',
    invoices: 'Invoices',
    quotes: 'Quotes',
    deliveryNotes: 'Delivery Notes',
    purchaseOrders: 'Purchase Orders',
    goodsReceipts: 'Goods Receipts',
    warehouses: 'Warehouses',
    stockMovements: 'Stock Movements',

    // Actions & Labels
    createInvoice: 'Create Invoice',
    createClient: 'Create Client',
    createQuote: 'Create Quote',
    createSupplier: 'Create Supplier',
    createArticle: 'Create Item',
    switchTheme: 'Switch Theme',
    switchLanguage: 'Switch Language',
    clientName: 'Client Name',
    supplierName: 'Supplier Name',
    itemName: 'Item Name',
    reference: 'Reference',
    raisonSociale: 'Company Name',
    matriculeFiscale: 'Tax ID',
    address: 'Address',
  },
  fr: {
    // General
    welcome: 'Bienvenue',
    guest: 'Invité',
    settings: 'Paramètres',
    logout: 'Déconnexion',
    dashboard: 'Tableau de bord',
    save: 'Enregistrer',
    saving: 'Enregistrement...',
    create: 'Créer',
    edit: 'Modifier',
    delete: 'Supprimer',
    cancel: 'Annuler',
    confirm: 'Confirmer',
    success: 'Succès',
    error: 'Erreur',
    requiredField: 'Ce champ est requis.',

    // Modules
    companySettings: 'Paramétrage Société',
    administration: 'Administration',
    purchases: 'Achat',
    sales: 'Vente',
    stock: 'Stock',
    finance: 'Finance',
    reporting: 'Pilotage',
    appSettings: 'Paramètres App',

    // Sub-modules & Screens
    companyInfo: 'Informations Société',
    employees: 'Employés',
    vehicles: 'Véhicules',
    banks: 'Banques',
    paymentMethods: 'Modes de Paiement',
    clients: 'Clients',
    suppliers: 'Fournisseurs',
    articles: 'Articles',
    itemFamilies: 'Familles d\'Articles',
    invoices: 'Factures',
    quotes: 'Devis',
    deliveryNotes: 'Bons de Livraison',
    purchaseOrders: 'Commandes Fournisseurs',
    goodsReceipts: 'Bons de Réception',
    warehouses: 'Dépôts',
    stockMovements: 'Mouvements de Stock',

    // Actions & Labels
    createInvoice: 'Créer une Facture',
    createClient: 'Créer un Client',
    createQuote: 'Créer un Devis',
    createSupplier: 'Créer un Fournisseur',
    createArticle: 'Créer un Article',
    switchTheme: 'Changer de Thème',
    switchLanguage: 'Changer de Langue',
    clientName: 'Nom du client',
    supplierName: 'Nom du fournisseur',
    itemName: 'Nom de l\'article',
    reference: 'Référence',
    raisonSociale: 'Raison Sociale',
    matriculeFiscale: 'Matricule Fiscale',
    address: 'Adresse',
  },
  ar: {
    // General
    welcome: 'أهلاً بك',
    guest: 'زائر',
    settings: 'الإعدادات',
    logout: 'تسجيل الخروج',
    dashboard: 'لوحة التحكم',
    save: 'حفظ',
    saving: 'جاري الحفظ...',
    create: 'إنشاء',
    edit: 'تعديل',
    delete: 'حذف',
    cancel: 'إلغاء',
    confirm: 'تأكيد',
    success: 'نجاح',
    error: 'خطأ',
    requiredField: 'هذا الحقل مطلوب.',

    // Modules
    companySettings: 'إعدادات الشركة',
    administration: 'الإدارة',
    purchases: 'المشتريات',
    sales: 'المبيعات',
    stock: 'المخزون',
    finance: 'المالية',
    reporting: 'التقارير',
    appSettings: 'إعدادات التطبيق',

    // Sub-modules & Screens
    companyInfo: 'معلومات الشركة',
    employees: 'الموظفون',
    vehicles: 'المركبات',
    banks: 'البنوك',
    paymentMethods: 'طرق الدفع',
    clients: 'العملاء',
    suppliers: 'الموردون',
    articles: 'الأصناف',
    itemFamilies: 'عائلات الأصناف',
    invoices: 'الفواتير',
    quotes: 'عروض الأسعار',
    deliveryNotes: 'مذكرات التسليم',
    purchaseOrders: 'أوامر الشراء',
    goodsReceipts: 'إيصالات البضائع',
    warehouses: 'المستودعات',
    stockMovements: 'حركات المخزون',
    
    // Actions & Labels
    createInvoice: 'إنشاء فاتورة',
    createClient: 'إضافة عميل',
    createQuote: 'إنشاء عرض سعر',
    createSupplier: 'إضافة مورد',
    createArticle: 'إضافة صنف',
    switchTheme: 'تغيير المظهر',
    switchLanguage: 'تغيير اللغة',
    clientName: 'اسم العميل',
    supplierName: 'اسم المورد',
    itemName: 'اسم الصنف',
    reference: 'المرجع',
    raisonSociale: 'اسم الشركة',
    matriculeFiscale: 'المعرف الضريبي',
    address: 'العنوان',
  },
};

// --- NOUVELLE PALETTE DE COULEURS ---
export const themes = {
  light: {
    background: '#F3F4F6', // Gris très clair
    card: '#FFFFFF',
    text: '#111827', // Presque noir
    textSecondary: '#6B7280', // Gris moyen
    primary: '#3B82F6', // Bleu vif
    primarySoft: '#EFF6FF', // Bleu très clair
    border: '#E5E7EB',
    success: '#10B981',
    danger: '#EF4444',
    buttonText: '#FFFFFF',
    sidebarBackground: '#111827',
    sidebarText: '#E5E7EB',
    sidebarActiveBackground: '#3B82F6',
    sidebarActiveText: '#FFFFFF',
  },
  dark: {
    background: '#1F2937', // Bleu nuit
    card: '#374151',
    text: '#F9FAFB', // Presque blanc
    textSecondary: '#9CA3AF',
    primary: '#60A5FA', // Bleu clair
    primarySoft: '#374151',
    border: '#4B5563',
    success: '#34D399',
    danger: '#F87171',
    buttonText: '#FFFFFF',
    sidebarBackground: '#111827',
    sidebarText: '#E5E7EB',
    sidebarActiveBackground: '#3B82F6',
    sidebarActiveText: '#FFFFFF',
  },
};